# Generated by theme.sh from JbXSLOt.jpg on 2026-05-18T09:30:23-07:00.
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "0a1519";
  BG_ALT = "0a1519";
  SURFACE = "59686e";
  BORDER = "03B5CB";
  BORDER_ACTIVE = "0D7688";
  BORDER_ACTIVE2 = "568180";
  BORDER_INACTIVE = "000105";
  ACCENT = "0D7688";
  TEXT = "c1c4c5";
  TEXT_DIM = "c1c4c5";
  BG_RGB = "10, 21, 25";
  BG_ALT_RGB = "10, 21, 25";
  ACCENT_RGB = "13, 118, 136";
  LOCK_BG = "10,21,25";
  LOCK_FG = "193,196,197";
  LOCK_C1 = "86,129,128";
  LOCK_C2 = "13,118,136";

  MOD_CLOCK = "79a1ec";
  MOD_WORLDCLOCK = "6ed6be";
  MOD_COOLING = "6ec1dd";
  MOD_NVIDIA = "6ecbbe";
  MOD_BATTERY = "6ecbbe";
  MOD_BATTERY_WARN = "97cbaf";
  MOD_BATTERY_CRIT = "97a7b4";
  MOD_BATTERY_CHARGE = "6ec1dd";
  MOD_NETWORK = "6ec1dd";
  MOD_NETWORK_DISC = "97a7b4";
  MOD_PULSEAUDIO = "97b6d3";
  MOD_CPU = "97c1b4";
  MOD_MEMORY = "83acdd";
  MOD_TEMP = "97b6d3";
  MOD_TEMP_CRIT = "97a7b4";
  MOD_BACKLIGHT = "97d6b4";
  MOD_REFRESHRATE = "97aa88";
  MOD_POWER = "97aa88";
  MOD_DISK = "6ec1dd";
  MOD_PLAYERCTL = "97b6d3";
  MOD_LAUNCHER = "50c9e3";
  MOD_RECORDER = "97a7b4";
}
