# Generated by theme.sh from 8ptxnpbe1g221.jpg on 2026-06-06T22:12:30-07:00.
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "140e20";
  BG_ALT = "140e20";
  SURFACE = "645d72";
  BORDER = "83788C";
  BORDER_ACTIVE = "435B76";
  BORDER_ACTIVE2 = "517599";
  BORDER_INACTIVE = "00000c";
  ACCENT = "435B76";
  TEXT = "c4c2c7";
  TEXT_DIM = "c4c2c7";
  BG_RGB = "20, 14, 32";
  BG_ALT_RGB = "20, 14, 32";
  ACCENT_RGB = "67, 91, 118";
  LOCK_BG = "20,14,32";
  LOCK_FG = "196,194,199";
  LOCK_C1 = "81,117,153";
  LOCK_C2 = "67,91,118";

  MOD_CLOCK = "a68cd6";
  MOD_WORLDCLOCK = "9bc0a8";
  MOD_COOLING = "9bacc7";
  MOD_NVIDIA = "9bb6a8";
  MOD_BATTERY = "9bb6a8";
  MOD_BATTERY_WARN = "c4b699";
  MOD_BATTERY_CRIT = "c4929e";
  MOD_BATTERY_CHARGE = "9bacc7";
  MOD_NETWORK = "9bacc7";
  MOD_NETWORK_DISC = "c4929e";
  MOD_PULSEAUDIO = "c4a1bd";
  MOD_CPU = "c4ac9e";
  MOD_MEMORY = "af97c7";
  MOD_TEMP = "c4a1bd";
  MOD_TEMP_CRIT = "c4929e";
  MOD_BACKLIGHT = "c4c09e";
  MOD_REFRESHRATE = "c49572";
  MOD_POWER = "c49572";
  MOD_DISK = "9bacc7";
  MOD_PLAYERCTL = "c4a1bd";
  MOD_LAUNCHER = "7db3cd";
  MOD_RECORDER = "c4929e";
}
