# Generated by theme.sh from flower.jpg on 2026-07-28T00:06:59-07:00.
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "0c0f1d";
  BG_ALT = "0c0f1d";
  SURFACE = "5c5f70";
  BORDER = "8B7A8B";
  BORDER_ACTIVE = "535568";
  BORDER_ACTIVE2 = "727387";
  BORDER_INACTIVE = "000009";
  ACCENT = "535568";
  TEXT = "c2c3c6";
  TEXT_DIM = "c2c3c6";
  BG_RGB = "12, 15, 29";
  BG_ALT_RGB = "12, 15, 29";
  ACCENT_RGB = "83, 85, 104";
  LOCK_BG = "12,15,29";
  LOCK_FG = "194,195,198";
  LOCK_C1 = "114,115,135";
  LOCK_C2 = "83,85,104";

  MOD_CLOCK = "a98cd6";
  MOD_WORLDCLOCK = "9dc1a8";
  MOD_COOLING = "9dacc7";
  MOD_NVIDIA = "9db7a8";
  MOD_BATTERY = "9db7a8";
  MOD_BATTERY_WARN = "c7b798";
  MOD_BATTERY_CRIT = "c7929d";
  MOD_BATTERY_CHARGE = "9dacc7";
  MOD_NETWORK = "9dacc7";
  MOD_NETWORK_DISC = "c7929d";
  MOD_PULSEAUDIO = "c7a2bd";
  MOD_CPU = "c7ac9d";
  MOD_MEMORY = "b297c7";
  MOD_TEMP = "c7a2bd";
  MOD_TEMP_CRIT = "c7929d";
  MOD_BACKLIGHT = "c7c19d";
  MOD_REFRESHRATE = "c79572";
  MOD_POWER = "c79572";
  MOD_DISK = "9dacc7";
  MOD_PLAYERCTL = "c7a2bd";
  MOD_LAUNCHER = "7fb4cc";
  MOD_RECORDER = "c7929d";
}
