# Generated by theme.sh from JbXSLOt.jpg on 2026-05-15T21:03:21-07:00.
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "0a1519";
  BG_ALT = "0a1519";
  SURFACE = "59686e";
  BORDER = "03B5CB";
  BORDER_ACTIVE = "0D7688";
  BORDER_ACTIVE2 = "568180";
  BORDER_INACTIVE = "000105";
  ACCENT = "0D7688";
  TEXT = "c1c4c5";
  TEXT_DIM = "c1c4c5";
  BG_RGB = "10, 21, 25";
  BG_ALT_RGB = "10, 21, 25";
  ACCENT_RGB = "13, 118, 136";
  LOCK_BG = "10,21,25";
  LOCK_FG = "193,196,197";
  LOCK_C1 = "86,129,128";
  LOCK_C2 = "13,118,136";
}
