# Generated by theme.sh from koi_dark.png on 2026-07-28T00:17:17-07:00.
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "100e20";
  BG_ALT = "100e20";
  SURFACE = "5f5d72";
  BORDER = "957685";
  BORDER_ACTIVE = "643D52";
  BORDER_ACTIVE2 = "797183";
  BORDER_INACTIVE = "00000c";
  ACCENT = "643D52";
  TEXT = "c3c2c7";
  TEXT_DIM = "c3c2c7";
  BG_RGB = "16, 14, 32";
  BG_ALT_RGB = "16, 14, 32";
  ACCENT_RGB = "100, 61, 82";
  LOCK_BG = "16,14,32";
  LOCK_FG = "195,194,199";
  LOCK_C1 = "121,113,131";
  LOCK_C2 = "100,61,82";

  MOD_CLOCK = "ad8bd4";
  MOD_WORLDCLOCK = "a1c0a6";
  MOD_COOLING = "a1abc5";
  MOD_NVIDIA = "a1b5a6";
  MOD_BATTERY = "a1b5a6";
  MOD_BATTERY_WARN = "cab596";
  MOD_BATTERY_CRIT = "ca919b";
  MOD_BATTERY_CHARGE = "a1abc5";
  MOD_NETWORK = "a1abc5";
  MOD_NETWORK_DISC = "ca919b";
  MOD_PULSEAUDIO = "caa0ba";
  MOD_CPU = "caab9b";
  MOD_MEMORY = "b696c5";
  MOD_TEMP = "caa0ba";
  MOD_TEMP_CRIT = "ca919b";
  MOD_BACKLIGHT = "cac09b";
  MOD_REFRESHRATE = "ca9470";
  MOD_POWER = "ca9470";
  MOD_DISK = "a1abc5";
  MOD_PLAYERCTL = "caa0ba";
  MOD_LAUNCHER = "83b3ca";
  MOD_RECORDER = "ca919b";
}
