general {
    lock_cmd = pidof hyprlock || (~/.config/hypr/hyprlock/hyprlock-run/panels; hyprlock)
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 2
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

listener {
    timeout = 300                           # in seconds
    #on-timeout = notify-send "You are idle!" # command to run when timeout has passed
    #on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}
