#!/usr/bin/env bash
# theme.sh — run pywal on a wallpaper, write palette.nix, rebuild.
#
# Home-manager reads palette.nix at eval time and interpolates the values
# into dotfile templates via builtins.replaceStrings. This script's only
# job is to derive the palette and emit the nix file.
#
# usage:
#   theme.sh                  use current awww wallpaper
#   theme.sh -i path/img.png  use arbitrary image
#   theme.sh -y               auto-accept (skip prompt)
#   theme.sh --preview        show palette only, do not write
#   theme.sh --dry-run        write palette.nix but skip yeet
#   theme.sh -h | --help

set -euo pipefail

DOTFILES="/etc/nixos/dotfiles"
PALETTE_NIX="$DOTFILES/palette.nix"
WAL_CACHE="$HOME/.cache/wal/colors.sh"
WAL_BIN="/etc/profiles/per-user/joe/bin/wal"
YEET="$DOTFILES/scripts/yeet.sh"

DRY=0
YES=0
PREVIEW=0
IMAGE=""

usage() { sed -n '2,15p' "$0" | sed 's/^# \?//'; exit 0; }
strip() { echo "${1#\#}"; }

hex_rgb_csv() {
    local h; h=$(strip "$1")
    printf "%d, %d, %d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}
hex_rgb_compact() {
    local h; h=$(strip "$1")
    printf "%d,%d,%d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}
darken() {
    local h; h=$(strip "$1"); local amt="${2:-30}"
    local r g b
    r=$(( 16#${h:0:2} - amt )); (( r < 0 )) && r=0
    g=$(( 16#${h:2:2} - amt )); (( g < 0 )) && g=0
    b=$(( 16#${h:4:2} - amt )); (( b < 0 )) && b=0
    printf "%02x%02x%02x" $r $g $b
}
swatch() {
    local label="$1" hex="$2"
    local h; h=$(strip "$hex")
    local r=$(( 16#${h:0:2} )) g=$(( 16#${h:2:2} )) b=$(( 16#${h:4:2} ))
    printf "  \e[48;2;%d;%d;%dm        \e[0m  #%s  %s\n" "$r" "$g" "$b" "$h" "$label"
}

get_wallpaper() {
    local wp
    wp=$(awww query 2>/dev/null \
        | grep -m1 'currently displaying: image:' \
        | sed -E 's/.*currently displaying: image:[[:space:]]*//')
    if [[ -z "$wp" || ! -f "$wp" ]]; then
        echo "error: could not determine wallpaper from 'awww query'" >&2
        exit 1
    fi
    echo "$wp"
}
run_wal() {
    echo "→ pywal on: $(basename "$1")"
    "$WAL_BIN" -i "$1" -n -q
    [[ -f "$WAL_CACHE" ]] || { echo "error: wal produced no $WAL_CACHE" >&2; exit 1; }
}

load_palette() {
    set +u
    # shellcheck source=/dev/null
    source "$WAL_CACHE"
    BG=$(strip "$background")
    BG_ALT=$(strip "$color0")
    SURFACE=$(strip "$color8")
    BORDER=$(strip "$color5")
    BORDER_ACTIVE=$(strip "$color1")
    BORDER_ACTIVE2=$(strip "$color4")
    BORDER_INACTIVE=$(darken "$color0" 20)
    ACCENT=$(strip "$color1")
    TEXT=$(strip "$foreground")
    TEXT_DIM=$(strip "$color7")
    BG_RGB=$(hex_rgb_csv "$BG")
    BG_ALT_RGB=$(hex_rgb_csv "$BG_ALT")
    ACCENT_RGB=$(hex_rgb_csv "$ACCENT")
    LOCK_BG=$(hex_rgb_compact "$background")
    LOCK_FG=$(hex_rgb_compact "$foreground")
    LOCK_C1=$(hex_rgb_compact "$color4")
    LOCK_C2=$(hex_rgb_compact "$color1")
    set -u
}

show_palette() {
    echo ""
    echo "  new palette"
    echo "  ────────────────────────────────────────────────"
    swatch "bg"               "#$BG"
    swatch "bg_alt"           "#$BG_ALT"
    swatch "surface"          "#$SURFACE"
    swatch "border"           "#$BORDER"
    swatch "border_active"    "#$BORDER_ACTIVE"
    swatch "border_active2"   "#$BORDER_ACTIVE2"
    swatch "border_inactive"  "#$BORDER_INACTIVE"
    swatch "accent"           "#$ACCENT"
    swatch "text"             "#$TEXT"
    swatch "text_dim"         "#$TEXT_DIM"
    echo ""
    echo "  rgb triplets: bg=$BG_RGB  bg_alt=$BG_ALT_RGB  accent=$ACCENT_RGB"
    echo "  hyprlock:     bg=$LOCK_BG  fg=$LOCK_FG  c1=$LOCK_C1  c2=$LOCK_C2"
    echo ""
}

write_palette_nix() {
    cat > "$PALETTE_NIX" <<EOF
# Generated by theme.sh from $(basename "$IMAGE") on $(date -Iseconds).
# Do not edit by hand — re-run theme.sh to regenerate.
{
  BG = "$BG";
  BG_ALT = "$BG_ALT";
  SURFACE = "$SURFACE";
  BORDER = "$BORDER";
  BORDER_ACTIVE = "$BORDER_ACTIVE";
  BORDER_ACTIVE2 = "$BORDER_ACTIVE2";
  BORDER_INACTIVE = "$BORDER_INACTIVE";
  ACCENT = "$ACCENT";
  TEXT = "$TEXT";
  TEXT_DIM = "$TEXT_DIM";
  BG_RGB = "$BG_RGB";
  BG_ALT_RGB = "$BG_ALT_RGB";
  ACCENT_RGB = "$ACCENT_RGB";
  LOCK_BG = "$LOCK_BG";
  LOCK_FG = "$LOCK_FG";
  LOCK_C1 = "$LOCK_C1";
  LOCK_C2 = "$LOCK_C2";
}
EOF
    echo "→ wrote $PALETTE_NIX"
}

reload_live() {
    echo ""
    echo "→ reloading live config"
    command -v hyprctl >/dev/null 2>&1 && hyprctl reload >/dev/null && echo "  ✓ hyprctl reload"
    local bartoggle="$DOTFILES/scripts/bartoggle.sh"
    if [[ -x "$bartoggle" ]]; then
        "$bartoggle" >/dev/null 2>&1; sleep 0.2; "$bartoggle" >/dev/null 2>&1
        echo "  ✓ waybar restarted"
    fi
    if pgrep -x dunst >/dev/null; then
        pkill -x dunst; sleep 0.1
        setsid dunst >/dev/null 2>&1 < /dev/null & disown
        echo "  ✓ dunst restarted"
    fi
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)  usage ;;
        --preview)  PREVIEW=1; shift ;;
        --dry-run)  DRY=1; shift ;;
        -y|--yes)   YES=1; shift ;;
        -i)         IMAGE="$2"; shift 2 ;;
        *)          echo "unknown: $1"; usage ;;
    esac
done

[[ -n "$IMAGE" ]] || IMAGE=$(get_wallpaper)
[[ -f "$IMAGE" ]] || { echo "no such image: $IMAGE" >&2; exit 1; }

notify-send "Running pywal..." 2>/dev/null || true
run_wal "$IMAGE"
load_palette
show_palette

if [[ "$PREVIEW" == "1" ]]; then
    exit 0
fi

if [[ "$YES" != "1" ]]; then
    read -rp "  write palette.nix? [y/N] " c
    [[ "$c" =~ ^[Yy]$ ]] || { echo "aborted"; exit 0; }
fi

write_palette_nix

if [[ "$DRY" == "1" ]]; then
    echo "  [dry-run] skipping yeet"
    exit 0
fi

notify-send "Rebuilding..." 2>/dev/null || true
"$YEET"
notify-send "Rebuild completed" 2>/dev/null || true
reload_live
