$background = rgb(10,14,25)      # deep navy-black water
$foreground = rgb(193,194,197)  # koi wallpaper cream highlight
$color1 = rgb(81,60,98)        # dark slate-blue
$color2 = rgb(46,48,74)        # deep wine-mauve
