#################
### UNIVERSAL ###
#################
$body_font = 26
$huge_font = 132
$heading_font = 66
$large_font = 39
$small_font = 19
################
### TOP LEFT ###
################
$top_left_offset = -346, 186
$pw_box_offset = -346, 721
$un_box_offset = -346, 879
$pw_text_offset = 693, 800
$un_text_offset = 693, 959
$login_text_offset = -346, 1065
$hostname_text_offset = -346, 1197
$un_value_offset = 693, 919
$input_field_offset = 666, 721
$top_left_size = 640
$container_box_size = 534, 132
$input_field_size = 534, 106
###################
### BOTTOM LEFT ###
###################
$bottom_left_offset = -346, -346
$time_text_offset = -346, -1024
$uptime_ltext_offset = 727, 346
$uptime_rtext_offset = -1420, 346
$bottom_left_size = 320
#############
### RIGHT ###
#############
$right_offset = 346, 0
$right_bottom_box_offset = 346, 160
$network_box_offset = 199, 506
$bluetooth_box_offset = 492, 506
$power_box_offset = 346, 213
$image_offset = 346, 1145
$media_symbol_offset = 346, -774
$network_symbol_offset = 199, 585
$bluetooth_symbol_offset = 492, 585
$day_value_offset = 346, 986
$date_value_offset = 346, 933
$media_content_value_offset = 346, -826
$media_player_value_offset = 346, -866
$network_value_offset = 199, 545
$bluetooth_value_offset = 492, 545
$power_status_value_offset = 346, 266
$power_percent_value_offset = 346, 292
$power_indicator_value_offset = 346, 372
$right_size = 640
$right_bottom_box_size = 640, 720
$power_box_size = 534, 240
$connection_box_size = 240, 160
$image_size = 213
