#################
### UNIVERSAL ###
#################
$body_font = 32
$huge_font = 160
$heading_font = 80
$large_font = 48
$small_font = 24

################
### TOP LEFT ###
################
$top_left_offset = -416, 224
$pw_box_offset = -416, 864
$un_box_offset = -416, 1056
$pw_text_offset = 832, 960
$un_text_offset = 832, 1152
$login_text_offset = -416, 1280
$hostname_text_offset = -416, 1440
$un_value_offset = 832, 1104
$input_field_offset = 800, 864
$top_left_size = 768
$container_box_size = 640, 160
$input_field_size = 640, 128

###################
### BOTTOM LEFT ###
###################
$bottom_left_offset = -416, -416
$time_text_offset = -416, -1248
$uptime_ltext_offset = 928, 416
$uptime_rtext_offset = -1760, 416
$bottom_left_size = 384

#############
### RIGHT ###
#############
$right_offset = 416, 0
$right_bottom_box_offset = 416, 192
$network_box_offset = 240, 608
$bluetooth_box_offset = 592, 608
$power_box_offset = 416, 256
$image_offset = 416, 1376
$media_symbol_offset = 416, -928
$network_symbol_offset = 240, 704
$bluetooth_symbol_offset = 592, 704
$day_value_offset = 416, 1184
$date_value_offset = 416, 1120
$media_content_value_offset = 416, -992
$media_player_value_offset = 416, -1040
$network_value_offset = 240, 656
$bluetooth_value_offset = 592, 656
$power_status_value_offset = 416, 320
$power_percent_value_offset = 416, 352
$power_indicator_value_offset = 416, 448
$right_size = 768
$right_bottom_box_size = 768, 864
$power_box_size = 640, 288
$connection_box_size = 288, 192
$image_size = 256
